# Generated by Django 5.2.4 on 2025-07-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
