# Generated by Django 5.2.4 on 2025-08-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_remove_review_user_review_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
