# Generated by Django 5.2.4 on 2025-08-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='in_restaurant',
            field=models.BooleanField(default=False),
        ),
    ]
