# Generated by Django 5.2.4 on 2025-08-01 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_restaurant_address_restaurant_city_and_more'),
        ('user_profile', '0002_profile_in_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='restaurant',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurants.restaurant'),
        ),
    ]
